cluster:
  num_workers: 8
  num_gpus: 4
  num_nodes: 1

data:
  _target_: src.data.PixelDataModule
  train_root_dir: /path/to/dataset/train
  val_root_dir: /path/to/dataset/val
  batch_size: 256
  num_workers: ${cluster.num_workers}
  img_size: 256
  img_extension: "JPEG"
  train_transform_fn:
    _partial_: True
    _target_: src.data.imagenet_transform
    load_dino: True
    img_size: ${data.img_size}
  val_transform_fn:
    _partial_: True
    _target_: src.data.imagenet_transform
    load_dino: True
    img_size: ${data.img_size}
  collate_fn:
    _partial_: True
    _target_: torch.utils.data.default_collate

model:
  _target_: src.training_module.SiTTrainingModule
  network:
    _target_: src.jit_class_cond_network.JiT
    # base params
    num_blocks: 24
    embed_dim: 1024
    num_heads: 16
    patch_size: 16
    in_channels: 3
    out_channels: 3
    resolution: 256
    bottleneck_dim: 128
    jit_sa_weights_dropout_prob: 0.0
    jit_sa_projection_dropout_prob: 0.0
    jit_sa_do_qk_norm: True
    jit_ffn_expansion_factor: 4
    jit_ffn_dropout_prob: 0.0
    num_classes: 1000
    in_context_cls_length: 32
    in_context_start_idx: 8
    # self_cond params
    use_self_cond: True
    self_cond_in_dim: 768
    self_cond_out_dim: 768
    self_cond_drop_prob: 0.1
    self_cond_projector_dim: 2048
    self_cond_layer_idx: null
    use_layernorm_in_self_cond: True
  ema_network:
    _partial_: True
    _target_: ema_pytorch.EMA
    beta: 0.9999
    update_after_step: 0
    update_every: 1
    min_value: 0.9999
    include_online_model: False
  loss:
    _target_: src.training_module.JiTLoss
    self_cond_loss: ${model.network.use_self_cond}
    feature_loss_weight: 0.03
    t_eps: 5e-2
  sampler:
    _target_: src.sampler.JiTHeunSampler
    in_resolution: ${model.network.resolution}
    in_channels: ${model.network.in_channels}
    num_tokens: 256 # always check
    self_cond_in_dim: ${model.network.self_cond_in_dim}
    cfg_interval: [0.1, 1.0]
    t_eps: ${model.loss.t_eps}
  train_preprocessing:
    _target_: src.processing.PixelPreprocessing
    resolution: ${model.network.resolution}
    P_mean: -0.8
    P_std: 0.8
    unconditional_cond_drop_prob: 0.1
    null_condition: ${model.network.num_classes}
    load_dino: ${data.train_transform_fn.load_dino}
    dino_config: "b"
  val_preprocessing:
    _target_: src.processing.PixelPreprocessing
    resolution: ${model.network.resolution}
    P_mean: -0.8 # is ignored
    P_std: 0.8 # is ignored
    unconditional_cond_drop_prob: 0.1 # is ignored
    null_condition: ${model.network.num_classes}
    load_dino: ${data.train_transform_fn.load_dino}
    dino_config: "b"
  img_postprocessing:
    _target_: src.processing.PixelPostprocessing
  use_compile: True
  jit_optim: True
  true_dino_features_prob: 0.05
  model_type: "jit"

trainer:
  _target_: lightning.pytorch.Trainer
  accelerator: gpu
  devices: ${cluster.num_gpus}
  precision: bf16-mixed
  strategy: ddp
  num_nodes: ${cluster.num_nodes}
  max_steps: 250000
  check_val_every_n_epoch: null
  val_check_interval: 25000
  gradient_clip_val: null
  logger:
    _target_: lightning.pytorch.loggers.WandbLogger
    name: ${hydra:runtime.choices.model/model}_${now:%H-%M-%S}
    project: dinoforcing
    version: ${oc.env:SLURM_JOB_ID, null}
    log_model: False
    save_dir: ${artifacts_dir}
    group: ${trainer.logger.name}
  default_root_dir: ${artifacts_dir}/${trainer.logger.name}
  callbacks:
    - _target_: lightning.pytorch.callbacks.ModelCheckpoint
      dirpath: ${trainer.default_root_dir}
      save_last: True
      every_n_train_steps: 12500
      save_top_k: -1
      enable_version_counter: True
    - _target_: lightning.pytorch.callbacks.LearningRateMonitor
      logging_interval: step
    - _target_: src.callbacks.LogImageCallback
      num_resample: 4
      num_sampling_steps: 50
      log_after_n_steps: 25000
      num_total_images: 10

artifacts_dir: artifacts/${trainer.logger.project}
ckpt_path: null